FROM node:18-alpine

WORKDIR /app

# Install system dependencies
RUN apk add --no-cache curl git

# Copy package information
COPY package.json yarn.lock ./
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

# Install dependencies
RUN yarn install

# Copy the source code
COPY . .

# Build the project
RUN yarn build

# Set environment to test
ENV NODE_ENV=test

# Default command runs tests
CMD ["yarn", "test"] 